# Generated by Django 4.2 on 2023-05-09 07:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tournament', '0001_initial'),
        ('referee', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='referee',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='referee',
            name='referee',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='referee',
            unique_together={('referee', 'tournament')},
        ),
        migrations.RemoveField(
            model_name='referee',
            name='name',
        ),
    ]
