# Generated by Django 4.2 on 2023-05-08 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_customuser_email_customuser_groups_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PhoneNumberVerification',
        ),
    ]
