# Generated by Django 4.1.7 on 2023-04-15 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='second_id',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
