# Generated by Django 4.2 on 2023-05-22 04:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Player_Pitching_Record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('games', models.IntegerField(default=0)),
                ('games_started', models.IntegerField(default=0)),
                ('complete_games', models.IntegerField(default=0)),
                ('shutouts', models.IntegerField(default=0)),
                ('wins', models.IntegerField(default=0)),
                ('losses', models.IntegerField(default=0)),
                ('saves', models.IntegerField(default=0)),
                ('innings_pitched', models.FloatField(default=0)),
                ('batters_faced', models.IntegerField(default=0)),
                ('pitches_thrown', models.IntegerField(default=0)),
                ('hits_allowed', models.IntegerField(default=0)),
                ('home_runs_allowed', models.IntegerField(default=0)),
                ('walks_allowed', models.IntegerField(default=0)),
                ('hit_by_pitch', models.IntegerField(default=0)),
                ('strikeouts', models.IntegerField(default=0)),
                ('wild_pitches', models.IntegerField(default=0)),
                ('balks', models.IntegerField(default=0)),
                ('runs_allowed', models.IntegerField(default=0)),
                ('earned_runs_allowed', models.IntegerField(default=0)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='player.player_tournament')),
            ],
        ),
        migrations.CreateModel(
            name='Player_Batting_Record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('games', models.IntegerField(default=0)),
                ('plate_appearances', models.IntegerField(default=0)),
                ('at_bats', models.IntegerField(default=0)),
                ('single', models.IntegerField(default=0)),
                ('double', models.IntegerField(default=0)),
                ('triple', models.IntegerField(default=0)),
                ('home_run', models.IntegerField(default=0)),
                ('walks', models.IntegerField(default=0)),
                ('hit_by_pitch', models.IntegerField(default=0)),
                ('intentional_walks', models.IntegerField(default=0)),
                ('strikeouts', models.IntegerField(default=0)),
                ('sacrifice_hits', models.IntegerField(default=0)),
                ('sacrifice_flies', models.IntegerField(default=0)),
                ('runs', models.IntegerField(default=0)),
                ('RBIs', models.IntegerField(default=0)),
                ('steals', models.IntegerField(default=0)),
                ('caught_steals', models.IntegerField(default=0)),
                ('errors', models.IntegerField(default=0)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='player.player_tournament')),
            ],
        ),
    ]
