# Generated by Django 4.2 on 2023-05-25 07:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0002_delete_team_group_stats'),
        ('player', '0002_player_pitching_record_player_batting_record'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player_tournament',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='team.team_record'),
        ),
    ]
