# Generated by Django 4.2 on 2023-05-28 14:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0003_team_record_initial_registration'),
        ('player', '0003_alter_player_tournament_team'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player_tournament',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_player', to='team.team_record'),
        ),
    ]
