# Generated by Django 4.2 on 2023-06-22 07:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0004_alter_player_tournament_team'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player_tournament',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player', to='player.player'),
        ),
    ]
