# Generated by Django 4.2 on 2023-04-30 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='type',
            field=models.CharField(choices=[('총장배', '총장배'), ('종체', '종체')], max_length=3),
        ),
    ]
