# Generated by Django 4.2 on 2023-06-23 03:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0003_team_record_initial_registration'),
        ('player', '0005_alter_player_tournament_player'),
        ('tournament', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='batter_king',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='batter_king', to='player.player'),
        ),
        migrations.AddField(
            model_name='tournament',
            name='mvp',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mvp', to='player.player'),
        ),
        migrations.AddField(
            model_name='tournament',
            name='pitcher_king',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pitcher_king', to='player.player'),
        ),
        migrations.AddField(
            model_name='tournament',
            name='runner_up',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='runner_up', to='team.team'),
        ),
        migrations.AddField(
            model_name='tournament',
            name='third_place',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='third_place', to='team.team'),
        ),
        migrations.AddField(
            model_name='tournament',
            name='winner',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='winner', to='team.team'),
        ),
    ]
