# Generated by Django 4.2 on 2023-05-22 04:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0002_delete_team_group_stats'),
        ('tournament', '0001_initial'),
        ('group', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='tournament',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tournament', to='tournament.tournament'),
        ),
        migrations.CreateModel(
            name='Team_Group_Stats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_games', models.IntegerField(default=0)),
                ('win', models.IntegerField(default=0)),
                ('loss', models.IntegerField(default=0)),
                ('draw', models.IntegerField(default=0)),
                ('attack_innings', models.FloatField(default=0)),
                ('defense_innings', models.FloatField(default=0)),
                ('runs_earned', models.IntegerField(default=0)),
                ('runs_given', models.IntegerField(default=0)),
                ('team_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_record', to='team.team_record')),
            ],
        ),
    ]
