# Generated by Django 4.2 on 2023-05-28 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_at_bat_inning_order_player_game_records_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='gameDateTime',
            new_name='game_date_time',
        ),
        migrations.RenameField(
            model_name='game',
            old_name='gameName',
            new_name='game_name',
        ),
        migrations.RenameField(
            model_name='game',
            old_name='groupGame',
            new_name='group_game',
        ),
        migrations.RenameField(
            model_name='records',
            old_name='bottomBBs',
            new_name='bottom_BBs',
        ),
        migrations.RenameField(
            model_name='records',
            old_name='bottomIP',
            new_name='bottom_IP',
        ),
        migrations.RenameField(
            model_name='records',
            old_name='bottomErrors',
            new_name='bottom_errors',
        ),
        migrations.RenameField(
            model_name='records',
            old_name='bottomHits',
            new_name='bottom_hits',
        ),
        migrations.RenameField(
            model_name='records',
            old_name='bottomInnings',
            new_name='bottom_innings',
        ),
        migrations.RenameField(
            model_name='records',
            old_name='bottomRuns',
            new_name='bottom_runs',
        ),
        migrations.RenameField(
            model_name='records',
            old_name='losingPitcher',
            new_name='losing_pitcher',
        ),
        migrations.RenameField(
            model_name='records',
            old_name='savePitcher',
            new_name='save_pitcher',
        ),
        migrations.RenameField(
            model_name='records',
            old_name='topBBs',
            new_name='top_BBs',
        ),
        migrations.RenameField(
            model_name='records',
            old_name='topIP',
            new_name='top_IP',
        ),
        migrations.RenameField(
            model_name='records',
            old_name='topErrors',
            new_name='top_errors',
        ),
        migrations.RenameField(
            model_name='records',
            old_name='topHits',
            new_name='top_hits',
        ),
        migrations.RenameField(
            model_name='records',
            old_name='topInnings',
            new_name='top_innings',
        ),
        migrations.RenameField(
            model_name='records',
            old_name='topRuns',
            new_name='top_runs',
        ),
        migrations.RenameField(
            model_name='records',
            old_name='winningPitcher',
            new_name='winning_pitcher',
        ),
    ]
