# Generated by Django 4.2 on 2023-06-23 03:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_rename_gamedatetime_game_game_date_time_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='team2',
            new_name='away',
        ),
        migrations.RenameField(
            model_name='game',
            old_name='team1',
            new_name='home',
        ),
        migrations.RemoveField(
            model_name='game',
            name='team1_home',
        ),
    ]
