# Generated by Django 4.2 on 2023-05-09 07:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Team_Group_Stats',
        ),
    ]
