# Generated by Django 4.1.7 on 2023-04-07 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0002_remove_team_captain_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='nickname',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
