# Generated by Django 4.1.7 on 2023-04-15 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0003_team_nickname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='nickname',
        ),
        migrations.AddField(
            model_name='team_record',
            name='nickname',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
