# Generated by Django 4.1.7 on 2023-04-15 06:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0001_initial'),
        ('team', '0004_remove_team_nickname_team_record_nickname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team_record',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='group.group'),
        ),
    ]
