# Generated by Django 4.1.7 on 2023-04-16 06:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0002_alter_group_name'),
        ('team', '0005_alter_team_record_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='team_record',
            name='second_round',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='second_round', to='group.group'),
        ),
    ]
