# Generated by Django 4.1.7 on 2023-04-16 07:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0002_alter_group_name'),
        ('team', '0006_team_record_second_round'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team_record',
            name='group',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='group', to='group.group'),
        ),
    ]
